# Generated by Django 4.2.1 on 2023-07-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airQualityApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillist",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
